import type { Metadata } from "next";
import { PT_Serif,Roboto, Geist } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const pt = PT_Serif({
  subsets: ["latin"],
   weight: ["400", "700"],
  variable: "--font-ptserif",
});

const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
})


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="pt-br"
      className={cn(pt.variable, roboto.variable, "font-sans", geist.variable)}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
